"""Add screenshot_path to reviews table

Revision ID: e90096d9dd90
Revises: 35672222c72f
Create Date: 2025-06-26 18:39:17.510546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90096d9dd90'
down_revision: Union[str, Sequence[str], None] = '35672222c72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('screenshot_path', sa.String(), nullable=True))
    op.drop_index(op.f('ix_reviews_book_id'), table_name='reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reviews_book_id'), 'reviews', ['book_id'], unique=False)
    op.drop_column('reviews', 'screenshot_path')
    # ### end Alembic commands ###
